services:
  - type: web
    name: portal-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn user.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromDatabase: false
      - key: ALLOWED_HOSTS
        value: ""
    healthCheckPath: /
    autoDeploy: true
    repo: ""
